# .travis.yml for OSX inspired by:
# https://github.com/ruslo/sugar/blob/travis.macosx/.travis.yml

language:
  - objective-c

env:
  - NETWORKX_VERSION=1.6
  - NETWORKX_VERSION=1.7
  - NETWORKX_VERSION=1.8
  - NETWORKX_VERSION=LATEST

before_install:
#  - brew update
  - sudo easy_install pip
  - if [ $NETWORKX_VERSION = LATEST ]; then pip install networkx --user --use-mirrors; else pip install -q networkx==$NETWORKX_VERSION --user --use-mirrors; fi;

install:
#  - brew install cmake
#  - if [ $PYTHON = 2.7 ]; then brew install python; else brew install osx/python26.rb; fi;
  - python setup.py -q install --user

script:
  - python setup.py test
#  - /Users/travis/Library/Python/2.7/bin/gratelpy_test

notifications:
    email: false