# .travis.yml inspired by NetworkX's
# https://github.com/networkx/networkx/blob/master/.travis.yml

language: python

# NetworkX needs at least 2.6, so nothing we can do about that.
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "pypy"

env:
  - NETWORKX_VERSION=1.6
  - NETWORKX_VERSION=1.7
  - NETWORKX_VERSION=1.8
  - NETWORKX_VERSION=HEAD

before_install:
  - pip install -q networkx==$NETWORKX_VERSION --use-mirrors

script:
  - printenv PWD
  - python setup.py -q install
  - python setup.py test
  - cd /
  - printenv PWD
  - gratelpy_test

notifications:
    email: false