# .travis.yml for OSX inspired by:
# https://github.com/ruslo/sugar/blob/travis.macosx/.travis.yml

language:
  - objective-c

env:
  - PYTHON=2.7
#  - NETWORKX_VERSION=1.6
#  - NETWORKX_VERSION=1.7
#  - NETWORKX_VERSION=1.8
#  - NETWORKX_VERSION=LATEST

before_install:
#  - brew update
#  - if [ $NETWORKX_VERSION = LATEST ]; then pip install networkx --use-mirrors; else pip install -q networkx==$NETWORKX_VERSION --use-mirrors; fi;

install:
#  - brew install cmake
#  - if [ $PYTHON = 2.7 ]; then brew install python; else brew install osx/python26.rb; fi;
  - python setup.py install --user

script:
  - python setup.py test
  - /Users/travis/Library/Python/2.7/bin/gratelpy_test

notifications:
    email: false