# .travis.yml inspired by NetworkX's
# https://github.com/networkx/networkx/blob/master/.travis.yml

language: python

# NetworkX needs at least 2.6, so nothing we can do about that.
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "pypy"

before_install:
  - pip install -r requirements.txt --use-mirrors

script:
  - printenv PWD
  - python setup.py install
  - python setup.py test
  - cd /
  - printenv PWD
  - gratelpy_test

notifications:
    email: false